### PR TITLE
test: add bib vmdk test

### PR DESCRIPTION
**Pull request by henrywang**

### CODE REVIEW

**Comment by shi2wei3** [comment]
You can rebase this PR locally just in case there is any conflicts on merge.

**Comment by shi2wei3** [comment]
I'm not familiar with vmware test, but I did't find any pre-setup steps for the VMWare datacenter, it's that expected? and how would the tmt system connect to this vmware datacenter which used to create vm?

**Comment by henrywang** [comment]
> I'm not familiar with vmware test, but I did't find any pre-setup steps for the VMWare datacenter, it's that expected? and how would the tmt system connect to this vmware datacenter which used to create vm?

Datacenter, datastore, and network part have been configured already by ldu and boyang already. We can't change and just use it.

**Review by shi2wei3 — APPROVED** [review]

**Comment by henrywang** [comment]
bib tests passed, no regression in this PR.

**Pull request merged**
